services:
  api-docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      AUTH_USERNAME: "admin"
      AUTH_PASSWORD: "admin@12345#"
      AUTH_SESSION_SECRET: "change-this-long-random-secret"
    restart: unless-stopped
